support both python2 and python3 via six.moves
ViktorStiskala/django-shared-session pull request #8
Opened 2018-10-16 23:27 UTC by jguffey

As on tin,

I found that this project did not work locally because I am running Python 2.6, however in prod I run Python 3, so I thought I'd add support for both via `six`.

2018-10-17 09:30 UTC, ViktorStiskala requested changes
Hello Josh, thanks for the contribution. I would, however, recommend upgrading Python on your local machine, py3 has so much more to offer. It should be a pretty easy and straightforward process as there are many options how to install Python nowadays.

In order for this change to work correctly, could you please make the changes also to setup.py (`install_requires` and `classifiers`)?

2018-10-17 09:30 UTC, ViktorStiskala commented on shared_session/templatetags/shared_session.py
> +from six.moves.urllib.parse import urljoin
This requires `six` as a dependency in `setup.py` → `install_requires`.

2018-10-18 16:58 UTC, jguffey commented
hi @ViktorStiskala, thank you for the feedback. 

I'd love to support only 3, but I do require support for version 2 for now, as my migration to 3 is yet to be completed.

I think that I have added the correct requirements to `setup.py` but please do let me know if I'm missing anything else. I'm new to Python packages so it's possible.

Thanks!

2018-10-30 19:09 UTC, merged

2018-10-30 19:16 UTC, ViktorStiskala commented
Thanks for the contribution.

I've uploaded the current version to pypi, so you can now install it directly using `pip install --upgrade django-shared-session`.